INHERIT: docs/common/config.yml

site_name: "redtide"
site_url: "https://redtide.github.io"
site_description: "Personal website"

#copyright: "Copyright &copy; 2019 - 2023 redtide"
#repo_name: "GitHub"
#repo_url: "https://github.com/redtide.github.io"

extra:
  homepage: "/en/"
  social:
  - icon: "fontawesome/brands/github"
    link: "https://github.com/redtide/"
    name: "Me on GitHub"

nav:
- "en/index.md"
- Projects:
  - Notes: "/notes/en/"
  - X-AIR Wiki: "/wiki-x-air/en/"
